//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Authy.EmailService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EmailServiceSoap", Namespace="http://tempuri.org/")]
    public partial class EmailService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailWithBccOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelayEmailSendingOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelDelaySendingOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEmailByTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllEmailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EmailService() {
            this.Url = global::Authy.Properties.Settings.Default.Authy_EmailService_EmailService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event SendEmailWithBccCompletedEventHandler SendEmailWithBccCompleted;
        
        /// <remarks/>
        public event SendEmailCompletedEventHandler SendEmailCompleted;
        
        /// <remarks/>
        public event DelayEmailSendingCompletedEventHandler DelayEmailSendingCompleted;
        
        /// <remarks/>
        public event CancelDelaySendingCompletedEventHandler CancelDelaySendingCompleted;
        
        /// <remarks/>
        public event getEmailByTokenCompletedEventHandler getEmailByTokenCompleted;
        
        /// <remarks/>
        public event getAllEmailsCompletedEventHandler getAllEmailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmailWithBcc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendEmailWithBcc(string from, string[] to, string[] cc, string subject, string body, object[] ps, bool isBodyHtml, string[] bcc) {
            object[] results = this.Invoke("SendEmailWithBcc", new object[] {
                        from,
                        to,
                        cc,
                        subject,
                        body,
                        ps,
                        isBodyHtml,
                        bcc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailWithBccAsync(string from, string[] to, string[] cc, string subject, string body, object[] ps, bool isBodyHtml, string[] bcc) {
            this.SendEmailWithBccAsync(from, to, cc, subject, body, ps, isBodyHtml, bcc, null);
        }
        
        /// <remarks/>
        public void SendEmailWithBccAsync(string from, string[] to, string[] cc, string subject, string body, object[] ps, bool isBodyHtml, string[] bcc, object userState) {
            if ((this.SendEmailWithBccOperationCompleted == null)) {
                this.SendEmailWithBccOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailWithBccOperationCompleted);
            }
            this.InvokeAsync("SendEmailWithBcc", new object[] {
                        from,
                        to,
                        cc,
                        subject,
                        body,
                        ps,
                        isBodyHtml,
                        bcc}, this.SendEmailWithBccOperationCompleted, userState);
        }
        
        private void OnSendEmailWithBccOperationCompleted(object arg) {
            if ((this.SendEmailWithBccCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailWithBccCompleted(this, new SendEmailWithBccCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendEmail(string from, string[] to, string[] cc, string subject, string body, object[] ps, bool isBodyHtml) {
            object[] results = this.Invoke("SendEmail", new object[] {
                        from,
                        to,
                        cc,
                        subject,
                        body,
                        ps,
                        isBodyHtml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendEmailAsync(string from, string[] to, string[] cc, string subject, string body, object[] ps, bool isBodyHtml) {
            this.SendEmailAsync(from, to, cc, subject, body, ps, isBodyHtml, null);
        }
        
        /// <remarks/>
        public void SendEmailAsync(string from, string[] to, string[] cc, string subject, string body, object[] ps, bool isBodyHtml, object userState) {
            if ((this.SendEmailOperationCompleted == null)) {
                this.SendEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendEmailOperationCompleted);
            }
            this.InvokeAsync("SendEmail", new object[] {
                        from,
                        to,
                        cc,
                        subject,
                        body,
                        ps,
                        isBodyHtml}, this.SendEmailOperationCompleted, userState);
        }
        
        private void OnSendEmailOperationCompleted(object arg) {
            if ((this.SendEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendEmailCompleted(this, new SendEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelayEmailSending", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DelayEmailSending(EmailModel em) {
            object[] results = this.Invoke("DelayEmailSending", new object[] {
                        em});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DelayEmailSendingAsync(EmailModel em) {
            this.DelayEmailSendingAsync(em, null);
        }
        
        /// <remarks/>
        public void DelayEmailSendingAsync(EmailModel em, object userState) {
            if ((this.DelayEmailSendingOperationCompleted == null)) {
                this.DelayEmailSendingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelayEmailSendingOperationCompleted);
            }
            this.InvokeAsync("DelayEmailSending", new object[] {
                        em}, this.DelayEmailSendingOperationCompleted, userState);
        }
        
        private void OnDelayEmailSendingOperationCompleted(object arg) {
            if ((this.DelayEmailSendingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelayEmailSendingCompleted(this, new DelayEmailSendingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelDelaySending", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CancelDelaySending(string token) {
            object[] results = this.Invoke("CancelDelaySending", new object[] {
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelDelaySendingAsync(string token) {
            this.CancelDelaySendingAsync(token, null);
        }
        
        /// <remarks/>
        public void CancelDelaySendingAsync(string token, object userState) {
            if ((this.CancelDelaySendingOperationCompleted == null)) {
                this.CancelDelaySendingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelDelaySendingOperationCompleted);
            }
            this.InvokeAsync("CancelDelaySending", new object[] {
                        token}, this.CancelDelaySendingOperationCompleted, userState);
        }
        
        private void OnCancelDelaySendingOperationCompleted(object arg) {
            if ((this.CancelDelaySendingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelDelaySendingCompleted(this, new CancelDelaySendingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getEmailByToken", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmailModel getEmailByToken(string token) {
            object[] results = this.Invoke("getEmailByToken", new object[] {
                        token});
            return ((EmailModel)(results[0]));
        }
        
        /// <remarks/>
        public void getEmailByTokenAsync(string token) {
            this.getEmailByTokenAsync(token, null);
        }
        
        /// <remarks/>
        public void getEmailByTokenAsync(string token, object userState) {
            if ((this.getEmailByTokenOperationCompleted == null)) {
                this.getEmailByTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmailByTokenOperationCompleted);
            }
            this.InvokeAsync("getEmailByToken", new object[] {
                        token}, this.getEmailByTokenOperationCompleted, userState);
        }
        
        private void OngetEmailByTokenOperationCompleted(object arg) {
            if ((this.getEmailByTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEmailByTokenCompleted(this, new getEmailByTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAllEmails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmailModel[] getAllEmails(string privateKey) {
            object[] results = this.Invoke("getAllEmails", new object[] {
                        privateKey});
            return ((EmailModel[])(results[0]));
        }
        
        /// <remarks/>
        public void getAllEmailsAsync(string privateKey) {
            this.getAllEmailsAsync(privateKey, null);
        }
        
        /// <remarks/>
        public void getAllEmailsAsync(string privateKey, object userState) {
            if ((this.getAllEmailsOperationCompleted == null)) {
                this.getAllEmailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllEmailsOperationCompleted);
            }
            this.InvokeAsync("getAllEmails", new object[] {
                        privateKey}, this.getAllEmailsOperationCompleted, userState);
        }
        
        private void OngetAllEmailsOperationCompleted(object arg) {
            if ((this.getAllEmailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllEmailsCompleted(this, new getAllEmailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmailModel {
        
        private string tokenField;
        
        private bool isHtmlBodyField;
        
        private string expiredTimeField;
        
        private int delyTimeField;
        
        private string createdTimeField;
        
        private string[] tosField;
        
        private string[] ccsField;
        
        private string[] bccsField;
        
        private string fromField;
        
        private string subjectField;
        
        private string bodyField;
        
        private object[] bodyParametersField;
        
        private byte isMonitorField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHtmlBody {
            get {
                return this.isHtmlBodyField;
            }
            set {
                this.isHtmlBodyField = value;
            }
        }
        
        /// <remarks/>
        public string ExpiredTime {
            get {
                return this.expiredTimeField;
            }
            set {
                this.expiredTimeField = value;
            }
        }
        
        /// <remarks/>
        public int DelyTime {
            get {
                return this.delyTimeField;
            }
            set {
                this.delyTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedTime {
            get {
                return this.createdTimeField;
            }
            set {
                this.createdTimeField = value;
            }
        }
        
        /// <remarks/>
        public string[] Tos {
            get {
                return this.tosField;
            }
            set {
                this.tosField = value;
            }
        }
        
        /// <remarks/>
        public string[] Ccs {
            get {
                return this.ccsField;
            }
            set {
                this.ccsField = value;
            }
        }
        
        /// <remarks/>
        public string[] Bccs {
            get {
                return this.bccsField;
            }
            set {
                this.bccsField = value;
            }
        }
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public object[] BodyParameters {
            get {
                return this.bodyParametersField;
            }
            set {
                this.bodyParametersField = value;
            }
        }
        
        /// <remarks/>
        public byte IsMonitor {
            get {
                return this.isMonitorField;
            }
            set {
                this.isMonitorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendEmailWithBccCompletedEventHandler(object sender, SendEmailWithBccCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailWithBccCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailWithBccCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendEmailCompletedEventHandler(object sender, SendEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DelayEmailSendingCompletedEventHandler(object sender, DelayEmailSendingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DelayEmailSendingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelayEmailSendingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CancelDelaySendingCompletedEventHandler(object sender, CancelDelaySendingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelDelaySendingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelDelaySendingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getEmailByTokenCompletedEventHandler(object sender, getEmailByTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEmailByTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEmailByTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmailModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmailModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getAllEmailsCompletedEventHandler(object sender, getAllEmailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllEmailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllEmailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmailModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmailModel[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591